export function orientation(): string;
export const ua: string;
export const ie: boolean;
export const ie9: boolean;
export const ielt9: boolean;
export const webkit: boolean;
export const android: boolean;
export const android23: boolean;
export const mobile: boolean;
export const msPointer: boolean;
export const pointer: number | boolean;
export const opera: any;
export const gecko: boolean;
export const firefox: boolean;
export const chrome: boolean;
export const edge: boolean;
export const ie3d: boolean;
export const webkit3d: boolean;
export const gecko3d: boolean;
export const opera3d: boolean;
export const any3d: boolean;
export const mobileWebkit: boolean;
export const mobileWebkit3d: boolean;
export const mobileOpera: any;
export let retina: boolean;
export const touch: number | boolean;
